import enum
class SimVisualizerFlag(enum.IntFlags, export=False):
    NAME = 1
    SITUATIONS = ...
    SI_STATE = ...
    INTERACTION_QUEUE = ...
    SMALL_BUSINESS_SATISFACTION = ...
    SMALL_BUSINESS_REVIEWS = ...

class SimVisualizerData(enum.Int, export=False):
    NAME = 0
    SITUATIONS_SIM_IS_IN = ...
    SITUATION_JOBS = ...
    SITUATION_ROLES = ...
    SI_STATE_DATA = ...
    INTERACTION_QUEUE = ...
    SATISFACTION_RANKING = ...
    SATISFACTION_PERFORM_INTERACTION = ...
    SATISFACTION_WAIT_RATIO = ...
    SATISFACTION_INDEX_WAIT_RATIO = ...
    SATISFACTION_INTERACTION_COUNTER = ...
    SATISFACTION_BUFF_BUCKET_TOTALS = ...
    SATISFACTION_BUCKET_TOTAL = ...
    SATISFACTION_MARKUP_RATIO = ...
    REVIEWS_RESULT = ...
